### ISSUE TITLE
Рандомный цвет

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/lesson-18-js#1]
https://github.com/AnnLuschik/lesson-18-js/blob/dd0f3059154f18b8b597135921f7848d168ad818/script3.js#L8

Попробуй придумать, как генерировать рандомный цвет и можно ещё сделать два варианта - Когда рандомный элемент списка меняет цвет, а все остальные исходного цвета и можно сделать, чтобы каждую секунду рандомный элемент становился рандомного цвета и к исходному не возвращались, что-то типо палитры будет)

**Comment by AnnLuschik** [comment]
Добавлено.
